name: Go
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go:
          - 1.23

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      - name: Build & Test
        run: go test -v ./...
